server:
  port: 9081
spring:
  application:
    name: flight-bookings
  data:
    mongodb:
      uri: mongodb+srv://dhiraj2k10_db_user:xxxxxxx@learnprogramming.7yxb6n7.mongodb.net/Flights?retryWrites=true&w=majority
      auto-index-creation: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
